global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:
  # The job name is added as a label `job=` to any timeseries scraped from this config.
  - job_name: "wsl"
    static_configs:
      - targets: ["172.29.119.193:9100"]
  - job_name: "kafka cluster"
    static_configs:
      - targets: ["kafka-exporter:9308"]
  - job_name: "redis cluster"
    static_configs:
      - targets: ["redis-exporter:9121"]